"""ChromaDB embedding and document upsert operations.

Initialises a persistent ChromaDB client, creates or retrieves a
collection, and upserts document chunks with embeddings generated by
``sentence-transformers``.

Usage::

    from standards_ingestion.embedder import (
        init_chroma_client,
        get_or_create_collection,
        upsert_documents,
    )
    from standards_ingestion.parser import Document

    client = init_chroma_client()
    collection = get_or_create_collection(client)
    docs: list[Document] = [...]
    count = upsert_documents(docs, collection)
"""

from __future__ import annotations

from typing import Any


try:
    import chromadb
except ImportError as exc:  # pragma: no cover
    raise ImportError(
        "chromadb is required for the embedder module. "
        "Install it with: pip install chromadb"
    ) from exc

try:
    from sentence_transformers import SentenceTransformer
except ImportError as exc:  # pragma: no cover
    raise ImportError(
        "sentence-transformers is required for the embedder module. "
        "Install it with: pip install sentence-transformers"
    ) from exc

from standards_ingestion.parser import Document


def init_chroma_client(
    persist_directory: str = "data/chroma_db",
) -> chromadb.ClientAPI:  # type: ignore[return-value]
    """Initialise a persistent ChromaDB client.

    Args:
        persist_directory: Directory where ChromaDB stores its data.

    Returns:
        A configured ``chromadb.PersistentClient`` instance.

    Raises:
        RuntimeError: If the ChromaDB client cannot be initialised.
    """
    try:
        return chromadb.PersistentClient(path=persist_directory)  # type: ignore[return-value]
    except Exception as exc:
        raise RuntimeError(
            f"Failed to initialise ChromaDB client at {persist_directory}: {exc}"
        ) from exc


def get_or_create_collection(
    client: chromadb.ClientAPI,  # type: ignore[type-arg]
    name: str = "standards_collection",
) -> chromadb.Collection:
    """Get an existing collection or create a new one.

    Args:
        client: A ChromaDB client instance.
        name: Name of the collection to get or create.

    Returns:
        A ChromaDB collection object.
    """
    return client.get_or_create_collection(name=name)


def upsert_documents(
    docs: list[Document],
    collection: chromadb.Collection,
    model_name: str = "sentence-transformers/all-MiniLM-L6-v2",
) -> int:
    """Generate embeddings and upsert documents to a ChromaDB collection.

    For each document, generates an embedding using the specified
    sentence-transformers model and upserts it to the collection with
    metadata including standard name, clause reference, chunk index,
    and source URL.

    Args:
        docs: List of :class:`Document` objects to upsert.
        collection: Target ChromaDB collection.
        model_name: HuggingFace model name for embeddings.

    Returns:
        The number of documents successfully upserted.

    Raises:
        RuntimeError: If embedding generation or ChromaDB upsert fails.
    """
    if not docs:
        return 0

    model = SentenceTransformer(model_name)

    ids: list[str] = []
    embeddings: list[list[float]] = []
    metadatas: list[dict[str, Any]] = []
    documents: list[str] = []

    for idx, doc in enumerate(docs):
        standard_name = doc.metadata.get("standard_name", "unknown")
        source_url = doc.metadata.get("source_url", "")
        clause = doc.metadata.get("clause", "")

        doc_id = f"{standard_name}-{idx}"
        ids.append(doc_id)
        embeddings.append(model.encode(doc.page_content).tolist())  # type: ignore[arg-type]
        source_type = doc.metadata.get("source_type", "unknown")
        standard_category = doc.metadata.get("standard_category", "")

        metadatas.append(
            {
                "standard_name": standard_name,
                "chunk_index": idx,
                "source_url": source_url,
                "clause": clause,
                "source_type": source_type,
                "standard_category": standard_category,
            }
        )
        documents.append(doc.page_content)

    try:
        collection.upsert(
            ids=ids,
            embeddings=embeddings,  # type: ignore[arg-type]
            metadatas=metadatas,  # type: ignore[arg-type]
            documents=documents,
        )
    except Exception as exc:
        raise RuntimeError(
            f"Failed to upsert {len(docs)} documents to ChromaDB: {exc}"
        ) from exc

    return len(docs)
